openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for hello
paths:
    /add/person:
        post:
            tags:
                - user
            summary: addPerson user
            operationId: user#addPerson
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Person'
                        example:
                            age: 868744758025898707
                            email: rahsaan@considine.biz
                            id: 6799014544609854512
                            mobileNo: Blanditiis voluptatem distinctio sed.
                            name: Praesentium harum laudantium illo consectetur ullam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example:
                                    - 81
                                    - 117
                                    - 111
                                    - 100
                                    - 32
                                    - 101
                                    - 115
                                    - 116
                                    - 32
                                    - 118
                                    - 101
                                    - 114
                                    - 111
                                    - 32
                                    - 112
                                    - 97
                                    - 114
                                    - 105
                                    - 97
                                    - 116
                                    - 117
                                    - 114
                                    - 32
                                    - 101
                                    - 115
                                    - 116
                                    - 46
                                format: binary
                            example:
                                - 86
                                - 101
                                - 108
                                - 105
                                - 116
                                - 32
                                - 97
                                - 114
                                - 99
                                - 104
                                - 105
                                - 116
                                - 101
                                - 99
                                - 116
                                - 111
                                - 32
                                - 110
                                - 97
                                - 109
                                - 46
    /hello/{name}:
        get:
            tags:
                - hello
            summary: sayHello hello
            operationId: hello#sayHello
            parameters:
                - name: name
                  in: path
                  description: Name to greet
                  required: true
                  schema:
                    type: string
                    description: Name to greet
                    example: Autem enim.
                  example: Nostrum consequatur.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: A greeting message
                                example: Placeat nihil ab ullam veniam qui.
                            example: Commodi deleniti debitis sapiente in enim.
    /printPerson:
        post:
            tags:
                - user
            summary: printPerson user
            operationId: user#printPerson
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Person'
                        example:
                            age: 962588955710604653
                            email: eva@olsonkuhlman.com
                            id: 7578785269693231749
                            mobileNo: Temporibus occaecati suscipit aspernatur.
                            name: Quis aspernatur expedita molestias et iure neque.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    1869668876:
                                        age: 6548943031786787644
                                        email: millie@schuster.name
                                        id: 7486465580686565503
                                        mobileNo: Dolorem deserunt.
                                        name: Consequatur aut consequuntur sed.
                                additionalProperties:
                                    $ref: '#/components/schemas/Person'
                            example:
                                94527046:
                                    age: 6548943031786787644
                                    email: millie@schuster.name
                                    id: 7486465580686565503
                                    mobileNo: Dolorem deserunt.
                                    name: Consequatur aut consequuntur sed.
                                156694314:
                                    age: 6548943031786787644
                                    email: millie@schuster.name
                                    id: 7486465580686565503
                                    mobileNo: Dolorem deserunt.
                                    name: Consequatur aut consequuntur sed.
    /user/{id}:
        get:
            tags:
                - user
            summary: getUser user
            operationId: user#getUser
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Est magnam nisi.
                  example: Consequatur fugit.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Velit enim atque doloribus rerum cupiditate consectetur.
                            example: Molestias culpa tenetur.
components:
    schemas:
        Person:
            type: object
            properties:
                age:
                    type: integer
                    example: 5111042497677084498
                    format: int64
                email:
                    type: string
                    example: alejandra.stamm@quigley.com
                    format: email
                id:
                    type: integer
                    example: 5305863361400602543
                    format: int64
                mobileNo:
                    type: string
                    example: Libero est aspernatur qui enim.
                name:
                    type: string
                    example: Dignissimos sapiente veniam voluptatum aut magni vitae.
            description: Person struct
            example:
                age: 535486291330675518
                email: lue_goyette@gleichner.biz
                id: 6438104226857935592
                mobileNo: Voluptatem cumque ut.
                name: Earum repellendus autem sed quo.
tags:
    - name: hello
      description: A simple service that says hello.
    - name: user
